name: Run Columbina Bot

on:
  workflow_dispatch:  
  push:
    branches:
      - main     
  schedule:
    - cron: "0 * * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Start Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: npm start